#ifndef HEARTBEAT_HPP
#define HEARTBEAT_HPP

#include "CanParser_autogenerated.hpp"
#include "TaskManager.hpp"
/**
 * @brief Task meant for blinking builtin led and sending heartbeat info to the
 * CAN bus. It works with 1s periodicity. In heartbeat info we have up time,
 * count of failed TxMessages to CAN and count of failed RxMessages to CAN.
 */
namespace SBT::System::Tasks {

struct Heartbeat : public SBT::System::PeriodicTask {
    Heartbeat();
    void initialize() override;
    void run() override;

    uint8_t payload[8];
    SBT::System::Comm::HEARTBEAT_t data;
};

} // namespace SBT::System::Tasks

#endif
