#ifndef F1XX_PROJECT_TEMPLATE_LIB_SBT_SDK_F1XX_SBT_SDK_SYSTEM_CanID_autogenerated_H
#define F1XX_PROJECT_TEMPLATE_LIB_SBT_SDK_F1XX_SBT_SDK_SYSTEM_CanID_autogenerated_H

#include <cstdint>

/** * !!!WARNING!!!
 * This file is autogenerated, any changes will not be retained after next
 * generation.
 *
 * @brief In this file are Source, Param, Group, Message ID definitions.
 */

namespace SBT::System::Comm::CAN_ID {

enum class Source : uint8_t {
    DEFAULT = 0x00,
    MPPT_CONTROLLER_1 = 0x01,
    MPPT_CONTROLLER_2 = 0x02,
    LIFEPO4_CONTROLLER_1 = 0x03,
    LIFEPO4_CONTROLLER_2 = 0x04,
    MPPT_1 = 0x05,
    MPPT_2 = 0x06,
    MPPT_3 = 0x07,
    MPPT_4 = 0x08,
    LIFEPO4_1 = 0x09,
    LIFEPO4_2 = 0x0A,
    LIFEPO4_3 = 0x0B,
    LIFEPO4_4 = 0x0C,
    PUMPS_CONTROLLER = 0x0D,
    CPB_CONTROLLER = 0x0E,
    PiBox = 0x0F,
    GPS_CONTROLLER = 0x10,
    YOKE = 0x11,
    UNKNOWN
};

enum class Param : uint16_t {
    DEFAULT = 0x000,
    HEARTBEAT = 0x001,
    LIFEPO4_GENERAL = 0x002,
    LIFEPO4_CELLS_1 = 0x003,
    LIFEPO4_CELLS_2 = 0x004,
    LIFEPO4_CELLS_3 = 0x005,
    PUMPS_GENERAL = 0x006,
    EMBEDDED_BUS_DATA = 0x007,
    POWER_BUS_DATA = 0x008,
    PV_DATA = 0x009,
    MPPT_CHARGER_DATA = 0x00A,
    YIELD_DATA = 0x00B,
    GEODETIC_POSITION_1 = 0x00C,
    GEODETIC_POSITION_2 = 0x00D,
    NED_VELOCITY = 0x00E,
    NED_HEADING = 0x00F,
    YOKE_GENERAL = 0x010,
    PUMPS_THRESHOLD = 0x011,
    UNKNOWN
};

enum class Group : uint8_t {
    DEFAULT = 0x00,
    LIFEPO4_DATA = 0x01,
    MPPT_DATA = 0x02,
    UNKNOWN
};

struct Message_t {
    uint8_t priority;
    Param paramID;
    Group group;
};

namespace Message {

constexpr Message_t HEARTBEAT = {7, Param::HEARTBEAT, Group::DEFAULT};

constexpr Message_t LIFEPO4_GENERAL = {4, Param::LIFEPO4_GENERAL,
                                       Group::LIFEPO4_DATA};

constexpr Message_t LIFEPO4_CELLS_1 = {7, Param::LIFEPO4_CELLS_1,
                                       Group::LIFEPO4_DATA};

constexpr Message_t LIFEPO4_CELLS_2 = {7, Param::LIFEPO4_CELLS_2,
                                       Group::LIFEPO4_DATA};

constexpr Message_t LIFEPO4_CELLS_3 = {7, Param::LIFEPO4_CELLS_3,
                                       Group::LIFEPO4_DATA};

constexpr Message_t PUMPS_GENERAL = {5, Param::PUMPS_GENERAL, Group::DEFAULT};

constexpr Message_t EMBEDDED_BUS_DATA = {3, Param::EMBEDDED_BUS_DATA,
                                         Group::DEFAULT};

constexpr Message_t POWER_BUS_DATA = {3, Param::POWER_BUS_DATA, Group::DEFAULT};

constexpr Message_t PV_DATA = {5, Param::PV_DATA, Group::MPPT_DATA};

constexpr Message_t MPPT_CHARGER_DATA = {7, Param::MPPT_CHARGER_DATA,
                                         Group::MPPT_DATA};

constexpr Message_t YIELD_DATA = {7, Param::YIELD_DATA, Group::MPPT_DATA};

constexpr Message_t GEODETIC_POSITION_1 = {7, Param::GEODETIC_POSITION_1,
                                           Group::DEFAULT};

constexpr Message_t GEODETIC_POSITION_2 = {7, Param::GEODETIC_POSITION_2,
                                           Group::DEFAULT};

constexpr Message_t NED_VELOCITY = {6, Param::NED_VELOCITY, Group::DEFAULT};

constexpr Message_t NED_HEADING = {7, Param::NED_HEADING, Group::DEFAULT};

constexpr Message_t YOKE_GENERAL = {2, Param::YOKE_GENERAL, Group::DEFAULT};

constexpr Message_t PUMPS_THRESHOLD = {2, Param::PUMPS_THRESHOLD,
                                       Group::DEFAULT};

} // namespace Message

} // namespace SBT::System::Comm::CAN_ID

#endif