//
// Created by hubert25632 on 10.04.2022.
//

#ifndef F1XX_PROJECT_TEMPLATE_MINIV2_HPP
#define F1XX_PROJECT_TEMPLATE_MINIV2_HPP

// MiniMainboard V2

#define SBT_BSP_REMAP_CAN1

#define SBT_BSP_PORT_BASE_HP1 GPIOA_BASE
#define SBT_BSP_PIN_HP1       GPIO_PIN_8

#define SBT_BSP_PORT_BASE_HP2 GPIOB_BASE
#define SBT_BSP_PIN_HP2       GPIO_PIN_13

#define SBT_BSP_PORT_BASE_HP3 GPIOB_BASE
#define SBT_BSP_PIN_HP3       GPIO_PIN_15

#define SBT_BSP_PORT_BASE_HP4 GPIOB_BASE
#define SBT_BSP_PIN_HP4       GPIO_PIN_12

#endif // F1XX_PROJECT_TEMPLATE_MINIV2_HPP
